### ISSUE TITLE
Error when trying trainer.test

### ISSUE THREAD

**Issue by dkanrjsk18** [materialsvirtuallab/matgl#163] opened 2023-09-13 00:07 UTC
Hi, thank you for these amazing codes.
I tried to follow the example notebook file to train M3GNet potential. I added `trainer.test(model=lit_module, dataloaders=test_loader)` to test the model, but I got the `RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn`. I found from google that it can be due to `required_grad=False` in the Tensor, but the error had not occured during training and validation, so it might not the cause of the error. Could you help me out to solve this? Thanks!

**Comment by shyuep** [comment] 2023-09-13 13:59
@kenko911 Pls fix and add a test.

**Comment by kenko911** [comment] 2023-09-13 22:09
Hi @dkanrjsk18, sorry for the late reply, It seems to me that the problem is not coming from the code itself but from the initialization of torch lightning trainer. We somehow need to have the argument inference_mode=False so that we can perform gradient calculations like forces and stresses. I added this in our united test and added a short description in the example. I will close this issue and please let me know if any further questions. Thanks!!

**Closed by kenko911** 2023-09-13 22:09 UTC
Labels: bug
